### ISSUE TITLE
Unable to delete Japanese text correctly on the post screen.

### ISSUE THREAD

**Issue by kimymt** [PrimalHQ/primal-ios-app#92] opened 2023-08-23 10:52 UTC
## Bug Description
When trying to delete text in the middle of Japanese text input and conversion, the previously input text is duplicated. Please see the attached video.
https://github.com/PrimalHQ/primal-ios-app/assets/3525759/3fbf6837-f752-4fb7-9c3f-b79ba3f347da

### Reproduction procedure
Input text with a Japanese keyboard and press the Delete button during conversion.

### Expected behavior
If you try to delete in the middle of conversion, the text you have been typing will be deleted. No duplicate text is entered.

### Environment
iPhone12mini
iOS16.6 (latese stable ver.)

### Additional Context
None

**Comment by PavleKreator** [comment] 2023-08-23 10:58
Thanks @kimymt, this is a duplicate of #68

**Comment by kimymt** [comment] 2023-08-23 11:02
Oh I didn't check it before making report. Thanks for notifying me

**Comment by kimymt** [comment] 2023-08-23 11:03
@PavleKreator Should I close this issue? This is 1st time to use github, so I don't know how to behave here.

**Closed** 2023-12-07 14:26 UTC
Labels: bug
